// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var List$ReactHooksTemplate = require("./List.bs.js");

function App(Props) {
  var match = React.useState((function () {
          return "";
        }));
  var setTerm = match[1];
  var term = match[0];
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, React.createElement("input", {
                      id: "search",
                      placeholder: "Dude, just start typing!",
                      value: term,
                      onChange: (function ($$event) {
                          return Curry._1(setTerm, $$event.target.value);
                        })
                    })), React.createElement(List$ReactHooksTemplate.make, {
                  term: term
                }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
