// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

var places = /* array */[
  /* record */[
    /* id */"0155d046-ff03-4d52-a98e-e48c887116af",
    /* name */"Chez Olivier",
    /* desc */"French cuisine",
    /* img : record */[
      /* url */"https://media-cdn.tripadvisor.com/media/photo-o/10/d1/fd/43/caption.jpg",
      /* attr */"Mine",
      /* attrUrl */undefined
    ],
    /* address */"1 Rue du Pont, Paris, 01000",
    /* coord : record */[
      /* lat */10.10,
      /* lon */99.23
    ],
    /* phone */"+00342342844",
    /* email */"olivier1903@gmail.com"
  ],
  /* record */[
    /* id */"fccc9b96-d611-4df9-bee5-ea0097779ba1",
    /* name */"Très Branché",
    /* desc */"French modern cuisine",
    /* img : record */[
      /* url */"https://scontent-vie1-1.xx.fbcdn.net/v/t31.0-8/10750410_1514324315519572_5477618609869746935_o.jpg?_nc_cat=106&_nc_ht=scontent-vie1-1.xx&oh=4eb18f9c6278a04413862cc6a8a9d0a3&oe=5D472B7E",
      /* attr */"(c) Tr\xc3\xa8s Branch\xc3\xa9",
      /* attrUrl */"Does not matter"
    ],
    /* address */"Lysenka str. 4, Kiev 01030, Ukraine",
    /* coord : record */[
      /* lat */50.448889,
      /* lon */30.513333
    ],
    /* phone */"+380 44 278 6125",
    /* email */"http://tres-fr.com/en/"
  ],
  /* record */[
    /* id */"199c12be-e8b9-4064-b9c5-48d98dac1b94",
    /* name */"Alchemist Bar",
    /* desc */"Just a bar",
    /* img : record */[
      /* url */"https://media-cdn.tripadvisor.com/media/photo-w/10/f2/f3/bd/20170928-205332-largejpg.jpg",
      /* attr */"(c) Alchemist Bar",
      /* attrUrl */undefined
    ],
    /* address */"Shota Rustaveli, 12, Kiev 01023, Ukraine",
    /* coord : record */[
      /* lat */50.438611,
      /* lon */30.523056
    ],
    /* phone */"+380 96 008 7070",
    /* email */"https://www.facebook.com/AlchemistBarKiev"
  ]
];

function search(places, str) {
  return Belt_Array.keep(places, (function (p) {
                return p[/* name */1].includes(str);
              }));
}

var Resto = /* module */[
  /* places */places,
  /* search */search
];

exports.Resto = Resto;
/* No side effect */
