// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Data$ReactHooksTemplate = require("./Data.bs.js");

var places = Data$ReactHooksTemplate.Resto[/* places */0];

var imgStyle = {
  height: "80px",
  margin: "10px",
  width: "auto"
};

var gradient = {
  backgroundImage: "linear-gradient(grey, transparent)",
  height: "100%",
  padding: "20px 0 0 20px",
  width: "100%"
};

function getElements(places, term) {
  return Belt_Array.map(Data$ReactHooksTemplate.Resto[/* search */1](places, term), (function (p) {
                var liStyle = {
                  backgroundImage: "url(" + (p[/* img */3][/* url */0] + ")"),
                  backgroundPosition: "center"
                };
                var match = p[/* img */3][/* attrUrl */2];
                return React.createElement("li", {
                            key: p[/* id */0],
                            style: liStyle,
                            title: match !== undefined ? match : "No attribution"
                          }, React.createElement("span", {
                                style: gradient
                              }, p[/* name */1]));
              }));
}

var headerStyle = {
  color: "#444444",
  fontSize: "20px"
};

function List(Props) {
  var term = Props.term;
  var elements = getElements(places, term);
  return React.createElement(React.Fragment, undefined, React.createElement("span", undefined, React.createElement("h3", {
                      style: headerStyle
                    }, "My Lovely Restaurant List. Total: ", String(elements.length))), React.createElement("ul", undefined, elements));
}

var make = List;

exports.places = places;
exports.imgStyle = imgStyle;
exports.gradient = gradient;
exports.getElements = getElements;
exports.headerStyle = headerStyle;
exports.make = make;
/* react Not a pure module */
